### PR TITLE
add support for sctp_peer_addr_change notification

### PR DESCRIPTION
**Pull request by hoelscher**
Is it right that I can test this only when I have a multihomed socket?

### CODE REVIEW

**Comment by tuexen** [comment]
I would assume that you should be able to observe the state change from SCTP_ADDR_AVAILABLE to SCTP_ADDR_UNREACHABLE even in the case of single-homing. Doesn't that work?

**Comment by hoelscher** [comment]
Ok, i will test that

**Comment by tuexen** [comment]
OK. Let me know if it doesn't work... Once the peer address is in the state SCTP_ADDR_UNREACHABLE and a HB/HB-ACK is successful, you should also
observe a state change from SCTP_ADDR_UNREACHABLE to SCTP_ADDR_AVAILABLE.
Again: If it doesn't work, let me know...

**Comment by hoelscher** [comment]
Test finished successfully.

**Comment by tuexen** [comment]
Thanks. Merged.

**Pull request merged**
